pages/modules/[module].tsx

For each module version, adds a link that leads to the directory in Github where the module lies to allow for easy inspection of the contents.

Add links to modules in GH repo

---

next.config.js
pages/all-modules.tsx
pages/index.tsx
pages/modules/[module].tsx
pages/search.tsx
public/CNAME

Reverts some of the changes from #7, in preparation for hosting under registry.bazel.build

Revert to root basepath for registry.bazel.build

---

pages/index.tsx

It feels like "bzlmod" is implied that it's short for "bazel modules", so "bzlmod modules" doesn't make sense to me. Switches the title to "Home of all your bazel modules!"

fix: bzlmod modules -> bazel modules

---

package.json
pages/modules/[module].tsx
pages/modules/[module]/[version].tsx
pnpm-lock.yaml

Addresses #16
I'm not sure whether we can assume that all versions follow the SemVer format (e.g. `abseil-cpp` doesn't), the used library (`compare-versions`) seem to handle this case fine, and at least for all the currently contained modules produces a sensible sorting.

Sort versions interpreted as SemVer versions

---

pages/modules/[module].tsx

CLOSES #16 (and #24 if merged before #25)
- Only shows the 5 most recent versions of a module on page load
- Below them, there is now a "Show all N versions" button, which will make the list expand to the full list of versions
- I opted for the simple one-time click rather than pagination, as it is a lot simpler to implement and reason about

Only show first 5 versions of module on page load

---

data/moduleStaticProps.ts
data/utils.ts
pages/modules/[module].tsx
pages/modules/[module]/[version].tsx
pages/modules/moduleStaticProps.ts

CLOSES #23 
Adds a small warning heading to all yanked versions that displays the yank "comment" (I couldn't find a documentation on what the value in the `yanked_versions` dictionary stands for, but that's what the first yanked modules used them for).
Example:

Add yank warning to yanked module versions

---

pages/modules/[module].tsx

I thought 'view in repository' would take me to the ruleset repo, but it goes to the registry repo

chore: clarify wording on link

---

components/CopyCode.tsx
data/utils.ts
pages/modules/[module].tsx

This assumes that the tag on the github repo has a 'v' prefix, which isn't required. I don't think we have enough information from BCR to know any better however.
Fixes #35

feat: show link to release notes

---

components/Footer.tsx

As requested by @meteorcloudy, adds link with report instructions to the footer (and while I was already there, I added a link to the bcr_ui repo as well).

Add links to report and website source to footer

---

pages/modules/[module].tsx

This fixes
```
Warning: Each child in a list should have a unique "key" prop.
Check the top-level render call using <ul>. See https://reactjs.org/link/warning-keys for more information.
```
on a modules details page.

Fix unique key for maintainer list

---

data/utils.ts

Modules such as https://registry.bazel.build/modules/apple_rules_lint don't have the `compatibility_level` set in their MODULE.bazel files. This is fine, since that is an optional attr with a default, see https://bazel.build/rules/lib/globals#module
However, querying for that attr returns `(missing)`, which is parsed to `NaN` and leads to the dreaded "hydration error" in next js during development, and of course to nothing being rendered in the final output in prod.
Falling back to the default of `0` fixes that.

Fix broken compatibility level when not specified

---

pages/search.tsx

I find that not showing anything at all when no matches are found is not really confidence inspiring for some reason. I really prefer having a "no matches found" text of some sort.
Closes #34

Add text when not finding any search results

---

pages/search.tsx

```
99:36  Error: `"` can be escaped with `&quot;`, `&ldquo;`, `&#34;`, `&rdquo;`.  react/no-unescaped-entities
100:73  Error: `"` can be escaped with `&quot;`, `&ldquo;`, `&#34;`, `&rdquo;`.  react/no-unescaped-entities
```
I introduced those accidentally with #43, see failing deploy on main branch

Fix lints for unescaped quotes

---

.prettierignore
README.md
components/Footer.tsx
package.json
pages/modules/[module].tsx
tailwind.config.js

I noticed that my editor (which is configured to run prettier on save) and the checked in code sometimes disagreed.
Turns out, while prettier is a dev-dependency, it isn't enforced in any way and there were no easy to discover entrypoints in the package file.
This adds
* `npm run prettier-check`
* `npm run prettier-fix`
the first of which we could run in a github workflow if you agree.

Configure & run prettier

---

data/moduleStaticProps.ts
package.json
pages/modules/[module].tsx
pages/modules/[module]/[version].tsx
pnpm-lock.yaml

FIXES #54
- Bump `compare-versions` to latest version
- Split out versions that are non-semver compliant before sorting for the time being

Hotfix version parsing breaking build by ignoring non-semver

---

data/moduleStaticProps.ts

Fixes a change resulting from #55

Fix wrong version being considered latest version after SemVer sorting changes

---

components/ModuleCard.tsx
data/moduleStaticProps.ts
data/utils.ts
pages/all-modules.tsx
pages/index.tsx
pages/modules/[module].tsx
pages/modules/[module]/[version].tsx

CLOSES #27
This will render all relative dates present on the pages again in the browser, so that they show the correct relative values to the current time. As this leads to a DOM that differs from the server-rendered DOM, we need to use `suppressHydrationWarning` for the rendering locations. Without that, we would get some React errors, leading to e.g. broken navigation.
As we now base all rendering on `authorDateIso`, the redundant old variants that contained the pre-rendered relative date string have been removed from the `staticProps`, reducing the size of the data blob that will be served to the frontend.
-----
Flow to test (might be easier with `libfaketime`, but I didn't get that to be respected in the Next.js build):
- Set system time to a value that is close to the latest BCR …

Re-render relative dates on client side to display correct value

---

pages/modules/[module].tsx

Add explainer links for yanked versions & compatibility levels, indicated by a dashed underline:
CLOSES #30

Add explainer links for yanked versions & compatibility levels

---

pages/modules/[module].tsx

Moves away from the circular design for the version number, which only really worked for strict semver number with no more than 4 digits in total. As we do have quite a few non-semver version numbers and pre-releases, the new style provides some more space to accommodate those.
The hover effect is adjusted to a highlight on the right border.
Old:
New:
(Includes #60, and is supposed to be merged after it)

 Adjust version number styling to provie more space

---

.github/workflows/deploy.yml

Build is failing after #72, where I accidentally updated the lockfile with a newer version of pnpm.
Rather than rolling it back, let's upgrade to the latest version of pnpm.

Bump pnpm to 8.6.12

---

pages/modules/[module].tsx

Makes the sidebar wrap once the screen is small-ish (using the technique describe on https://every-layout.dev/layouts/sidebar/).
<details>
<summary>New</summary>
</details>
<details>
<summary>Old</summary>
</details>

Adjust module metadata sidebar to be responsive

---

WORKSPACE

There is an `http` URL in the `WORKSPACE`; probably copypasta 🍝 
Fixes and closes bazel-contrib/bcr-ui#101

fix: `http` url in workspace

---

WORKSPACE
data/utils.ts
pages/modules/[module].tsx

This PR adds a new section to the module detail page under the heading _Dependency graph_; in this section, accordions are shown for the package's dependency relationships:
- Transitive packages (the most meaningful to a package consumer)
- Dev packages (not meaningful to a package consumer, maybe meaningful to contributors)
- Dependents (lightly meaningful to all stakeholders)
This UI optimizes for the above goals, with the _Transitive_ package accordion **open by default**, and the others closed, but with **counts added** so that a package's popularity / relevance in the wider package graph can be understood with a quick glance.
_Background:_ I just shipped [`rules_graalvm`](https://registry.bazel.build/modules/rules_graalvm), my first BCR package. Due to the polyglot nature of GraalVM, …

feat: distinguish types of dependencies

---

styles/globals.css

Enhances #103 by applying the following to accordion UI (`details summary` elements):
- `cursor: pointer`
- `user-select: none`
| **Before** | **After** |
| ---------- | --------- |
| <img width="497" alt="Screenshot 2023-09-11 at 5 30 03 PM" src="https://github.com/bazel-contrib/bcr-ui/assets/171897/3d4ecff7-b0ae-4f01-9210-ab8afe420e26"> | <img width="498" alt="Screenshot 2023-09-11 at 5 30 15 PM" src="https://github.com/bazel-contrib/bcr-ui/assets/171897/da3b192b-85ba-4a2b-b749-a4758c129024"> |
> Video preview down below 👇🏻 
- fix: use `cursor: pointer` for `details summary` elements
- fix: use `user-select: none` to prevent accidental highlight of accordion summary elements

fix: `cursor: pointer` for dependency accordions

---

data/utils.ts

I noticed that especially the build times for pages with a lot of releases (e.g. `aspect_bazel_lib`) were getting slower. As for those modules, there are also more pages to be built, this led to quadratic build time increases.
This memoizes the function that determines the commit on the BCR that corresponds to a release being published, which allows the result to be reused across pages.
For me locally that reduced the total build time from ~80s to ~20s!

Memoize determining git release commit

---

components/Header.tsx
pages/index.tsx
pages/search.tsx

FIXES #112
In general transitions from an `<input>` element that had special event handling to a `<input>` inside `<form>` which AFAIK is the better way to handle submits across platforms.
Also adjusts the navbar on mobile to have a visible and working search (there are still some navbar items for external links missing on mobile, but that was also the case before)

Fix mobile search

---

data/moduleStaticProps.ts
data/utils.ts
pages/modules/[module].tsx

Including `yanked_versions` and `maintainers`
Fixes https://github.com/bazel-contrib/bcr-ui/issues/134

Be resilient to certain missing fields in metadata.json

---

data/utils.ts

FIXES #140 
`pMemoize` only uses the first argument to cache by default, so we only determined one submisssion commit for a version of a module and then re-used the same commit for all versions of the module.
This adjusts it to use the full arguments (module name + module version) as the cache key.

Fix submission commit detection caching being too agressive

---

.github/workflows/deploy.yml

See https://github.com/pnpm/action-setup/releases/tag/v2.4.1
Sample failure: https://github.com/bazel-contrib/bcr-ui/actions/runs/9878535597/job/27282696349
Fixes https://github.com/bazel-contrib/bcr-ui/issues/146

Fix "Install pnpm" error about "invalid this"

---

data/moduleStaticProps.ts

Got bored and wanted to explore Typescript.
Tested on https://typescriptlang.org/play:
> console.log(sortVersions(['1.2.3', '1.2.3-d', '1.2.3.bcr.1', '1.2.3rc3', '1', 'k']))
["k", "1.2.3rc3", "1.2.3.bcr.1", "1.2.3", "1.2.3-d", "1"] 
Partially addresses #54.
Fixes #142.

Implement proper version sorting

---

next.config.js

Looks like in on-bcr-trigger action was failing for last 3 days and there are stale results on the BCR page.
See also https://github.com/bazel-contrib/bcr-ui/issues/153

Increase static page generation timeout 60s -> 600s

---

pages/index.tsx

No one touched it for three years.
I simply picked the ones from https://github.com/orgs/bazel-contrib/repositories that have >300 stars.

Update "highlighted modules"

---

.github/workflows/test.yml

Also run test workflow on `pull_request` events. Not doing that is how #119 slipped by, as well as a prettier formatting issue that managed to slip into main.
I think this didn't surface earlier, as I was pushing to branches on this repository (and not my fork), where tests were run correctly.

Adjust workflow to test pull requests 

---

components/AttestationBadge.tsx
components/ModuleCard.tsx
data/moduleStaticProps.ts
data/utils.ts
pages/all-modules.tsx
pages/index.tsx
pages/modules/[module].tsx
pages/search.tsx

A small checkmark is shown if the module has the attestation JSON file. I also added a small tooltip that shows up on hover that briefly explains the concept.

Add visual indicator for attestation

---

components/AttestationBadge.tsx

Looks like the tooltip is not showing up for some users as discussed [here](https://github.com/bazel-contrib/bcr-ui/pull/162). This approach should work in most browsers.

Fix tooltip on attestation badge

---

renovate.json

We get a lot of automated PRs and don't really care about staying on the latest of these packages. Reduce noise for maintainers.
Similar to https://github.com/bazelbuild/examples/pull/597

renovate: stop updating npm packages

---

components/AttestationBadge.tsx
components/CopyCode.tsx
pages/modules/[module].tsx
styles/globals.css
tailwind.config.js

Main section 
- Add contrast copy code section
- Show the attestation badge right next to module name if the selected version has it 
- Make attestation badge noticeable 
About section 
- Add License information from repo 
- Add star information from repo
- Add topics from repo
- Rename Metadata to About 
- Add contrast to links in About section and only change to green on hover and align icons vertically
- Pop Github and Email icons for maintainers on hover
Overall: 
Hover:
Hover:

feat: rework the module page

---

components/Stardoc.tsx
data/moduleStaticProps.ts
data/stardoc.ts
data/utils.ts
package.json
pages/modules/[module].tsx
pnpm-lock.yaml

Makes the module page wider, and beneath the existing two-column view, adds a full-width listing of stardocs if they are present on the module's source.json.
Fixes https://github.com/bazelbuild/bazel-central-registry/issues/5593

feat: render stardocs
